// Port of Assets/Scripts/WordSearch/WordBank.cs — keep in sync with that file.
const WORDS = [
  // Animals
  'CAT', 'DOG', 'LION', 'TIGER', 'BEAR', 'WOLF', 'EAGLE', 'HAWK', 'SHARK', 'WHALE',
  'DOLPHIN', 'ZEBRA', 'GIRAFFE', 'MONKEY', 'RABBIT', 'FOX', 'DEER', 'MOUSE', 'HORSE', 'SNAKE',
  'LIZARD', 'TURTLE', 'FROG', 'OWL', 'PANDA', 'KOALA', 'CAMEL', 'GOAT', 'SHEEP', 'OTTER',
  'CRAB', 'SQUID', 'OCTOPUS', 'PARROT', 'FALCON', 'BEAVER', 'PENGUIN', 'WALRUS', 'SEAL', 'STINGRAY',
  'JELLYFISH', 'LOBSTER', 'OYSTER', 'STARFISH', 'SEAHORSE',

  // Nature
  'TREE', 'RIVER', 'MOUNTAIN', 'OCEAN', 'FOREST', 'DESERT', 'VALLEY', 'ISLAND', 'CANYON', 'GLACIER',
  'VOLCANO', 'MEADOW', 'JUNGLE', 'PRAIRIE', 'WATERFALL', 'CLIFF', 'CORAL', 'REEF', 'STORM', 'THUNDER',
  'LIGHTNING', 'RAINBOW', 'CLOUD', 'BREEZE', 'TORNADO',

  // Sky and space
  'SUNRISE', 'SUNSET', 'HORIZON', 'ECLIPSE', 'PLANET', 'GALAXY', 'COMET', 'METEOR', 'STAR', 'MOON',
  'ORBIT', 'GRAVITY', 'NEBULA', 'ASTEROID', 'TELESCOPE', 'ROCKET', 'SATELLITE', 'ASTRONAUT', 'UNIVERSE', 'COSMOS',

  // Food
  'PIZZA', 'BURGER', 'PASTA', 'SALAD', 'BREAD', 'CHEESE', 'APPLE', 'BANANA', 'ORANGE', 'GRAPE',
  'MANGO', 'LEMON', 'CHERRY', 'PEACH', 'MELON', 'POTATO', 'CARROT', 'ONION', 'GARLIC', 'PEPPER',
  'TOMATO', 'CUCUMBER', 'SPINACH', 'BROCCOLI', 'COOKIE', 'CAKE', 'CANDY', 'HONEY', 'SYRUP', 'YOGURT',

  // Technology
  'COMPUTER', 'LAPTOP', 'PHONE', 'TABLET', 'ROBOT', 'INTERNET', 'NETWORK', 'SOFTWARE', 'HARDWARE', 'KEYBOARD',
  'MONITOR', 'PRINTER', 'CAMERA', 'SPEAKER', 'BATTERY', 'CIRCUIT', 'SENSOR', 'ANTENNA', 'BROWSER', 'WEBSITE',

  // Sports
  'SOCCER', 'TENNIS', 'HOCKEY', 'BOXING', 'GOLF', 'RUGBY', 'CRICKET', 'SWIMMING', 'RUNNING', 'CYCLING',
  'SKATING', 'SKIING', 'SURFING', 'ROWING', 'ARCHERY', 'FENCING', 'WRESTLING', 'BOWLING', 'DARTS', 'CHESS',
  'MARATHON', 'STADIUM', 'REFEREE', 'WHISTLE', 'TROPHY',

  // Colors and shapes
  'CRIMSON', 'AMBER', 'IVORY', 'SCARLET', 'MAROON', 'TEAL', 'CIRCLE', 'SQUARE', 'TRIANGLE', 'RECTANGLE',
  'OVAL', 'DIAMOND', 'HEXAGON', 'CUBE', 'SPHERE', 'CYLINDER', 'PENTAGON', 'OCTAGON', 'SPIRAL', 'PRISM',

  // Music
  'GUITAR', 'PIANO', 'VIOLIN', 'DRUMS', 'FLUTE', 'TRUMPET', 'CELLO', 'HARP', 'ORGAN', 'CLARINET',
  'MELODY', 'RHYTHM', 'CHORUS', 'ANTHEM', 'BALLAD',

  // Household
  'CHAIR', 'TABLE', 'SOFA', 'LAMP', 'MIRROR', 'PILLOW', 'BLANKET', 'CURTAIN', 'CARPET', 'CABINET',
  'DRAWER', 'SHELF', 'CLOCK', 'CANDLE', 'BASKET', 'LADDER', 'HAMMER', 'WRENCH', 'SCISSORS', 'BUCKET',

  // Jobs
  'DOCTOR', 'TEACHER', 'FARMER', 'PILOT', 'SAILOR', 'ARTIST', 'WRITER', 'DANCER', 'SINGER', 'LAWYER',
  'NURSE', 'DENTIST', 'PLUMBER', 'BAKER', 'BUTCHER', 'TAILOR', 'PAINTER', 'MECHANIC', 'ENGINEER', 'SCIENTIST',

  // Science
  'ATOM', 'MOLECULE', 'ELEMENT', 'ENERGY', 'MAGNET', 'CRYSTAL', 'MINERAL', 'FOSSIL', 'VIRUS', 'BACTERIA',
  'VACCINE', 'OXYGEN', 'HYDROGEN', 'CARBON', 'PROTON', 'NEURON', 'ENZYME', 'HORMONE', 'VITAMIN', 'PROTEIN',

  // Travel and places
  'AIRPORT', 'HARBOR', 'STATION', 'BRIDGE', 'TUNNEL', 'HIGHWAY', 'VILLAGE', 'CASTLE', 'PALACE', 'TEMPLE',
  'MUSEUM', 'LIBRARY', 'MARKET', 'GARDEN', 'PARK', 'PLAZA', 'FOUNTAIN', 'MONUMENT', 'LIGHTHOUSE', 'COMPASS',
];

module.exports = { WORDS };
